@startuml Statuts

title Diagramme de Classes - Statuts (Monstre & Terrain)

package "Statuts Monstre" {
    abstract class StatutMonstre {
        #labelStatut : String
        #nbToursEffet : int
        #nbToursAvecEffet : int

        +decrementerNbToursAvecEffet() : void
        +getLabelStatut() : String
    }

    class Brule extends StatutMonstre {
        +Brule()
        +appliquerEffets(Monstre, double) : void
    }

    class Paralyse extends StatutMonstre {
        -{static} CHANCE_RATER_ATTAQUE : double = 0.375
        -{static} NB_TOURS_MAX_PARALYSIE : int = 6

        +Paralyse()
        +rateAttaque(Monstre) : void
        +sortParalysie(Monstre) : void
        +appliquerEffets(Monstre, double) : void
    }

    class Empoisonne extends StatutMonstre {
        +Empoisonne()
        +appliquerEffets(Monstre, double) : void
    }

    class Normal extends StatutMonstre {
        +Normal()
    }

    class SousTerre extends StatutMonstre {
        -{static} NB_TOURS_MAX_FUITE : int = 3
        -{static} NB_TOURS_MIN_FUITE : int = 1

        +SousTerre()
        +appliquerEffets(Monstre) : void
        +sortirSousTerre(Monstre) : void
    }
}

package "Statuts Terrain" {
    abstract class StatutTerrain {
        #labelStatut : String
        #nbToursEffet : int
        #nbToursAvecEffet : int

        +decrementerNbToursAvecEffet() : void
        +getNbToursEffet() : int
        +getLabelStatut() : String
    }

    class Innonde extends StatutTerrain {
        -probabiliteFaireChuter : double
        -monstreSource : Monstre

        +Innonde(int, double, Monstre)
        +getMonstreSource() : Monstre
        +appliquerEffetsTerrain(Monstre, Terrain, double) : void
        +retraitInnondation(Terrain) : void
    }

    class Asseche extends StatutTerrain {
        +Asseche()
        +appliquerEffets(Terrain) : void
    }
}

@enduml
